name: Deploy to Google Storage

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.GKE_SA_KEY }}
          bucket: 'cv.rymar.work'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'