name: Deploy to GKE

on:
  workflow_dispatch:      

env:
  GKE_CLUSTER: main-cluster
  GKE_ZONE: europe-central2-a   
  DEPLOYMENT_NAME: rss 

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: 'upload-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: './'
          destination: 'cv.rymar.work'
          parent: false   